# Generated by Django 5.0.2 on 2024-02-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_alter_volunteer_volunteer_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerStatusMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['received_at'], name='volunteers__receive_1741d4_idx')],
            },
        ),
    ]
